unbroken-dome/gradle-helm-plugin

docs/config-from-project-properties.adoc
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmInstallOrUpgrade.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmRelease.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/rules/HelmInstallReleaseTaskRule.kt

Adding the --atomic flag so install and upgrade are rolled back automatically in case of failure. Maybe it could be release in 0.4.1

 * Added atomic flag to 'helm install' and 'helm upgrade'

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmInstallationOptions.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmInstallationCommandTask.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmRelease.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmInstallTest.kt

Added the --version option to generate flags and options for the helm install exec command, this patch covered #45 issue.

#45 Add --version option for helm install exec command

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmInstallationOptions.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmCommandTask.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmInstallationCommandTask.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmRelease.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmInstallTest.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmUpgradeTest.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/InstallationOptionsTests.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/release/HelmReleasesPluginTest.kt

Add support for the `--create-namespace` flag for install and upgrade… commands (introduced in Helm 3.2.0)

Add support for --create-namespace flag

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/tasks/HelmFilterSources.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/util/SimpleTemplateEngineFilterReader.kt

Gradle's built-in ContentFilterable.expand does not expose the escapeBackslashes option, so we need to provide our own transformer around SimpleTemplateEngine.
fixes #52

Fix: escape backslashes when filtering files

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/publishers/AbstractHttpHelmChartPublisher.kt

Like you can see here https://github.com/square/okhttp/blob/19771365f25d986d125478a75c15d24d6e285e12/okhttp/src/main/kotlin/okhttp3/Credentials.kt#L32 the http client is adding the keyword Basic already. This results into "Basic Basic xyz"

Fix basic authentication

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmServerCommandTask.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmAddRepository.kt

HelmAddRepository task: Change task property annotations from `@Input` to `@InputFile` for file properties (caFile, certificateFile and keyFile)
fixes #57

HelmAddRepository: fix annotations on file-valued properties

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecWorkAction.kt

Proposed fix for https://github.com/unbroken-dome/gradle-helm-plugin/issues/60

KUBECONFIG Environmental variable forwarded to Worker

---

docs/configure-helm.adoc
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecWorkAction.kt

- HelmExecWorkAction: update comment for passing `KUBECONFIG` (see PR #65)
- updated documentation regarding the use of `KUBECONFIG`

Update comment & documentation after PR #65

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecWorkAction.kt

Pass the PATH env var to the worker

fixes #74 by passing PATH env var in the worker action

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecWorkAction.kt

fixes #74 by passing PATH env var in the worker action
master already has new features merged in, so this back-merges the fix to 1.2.x

Back-merge PR #75 to 1.2.x version line

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/HelmDownloadClient.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/HelmExtension.kt

HelmDownloadClient: use ObjectFactory to construct nested object, to enable Groovy syntax for setting properties
fixes #73

Fix Groovy syntax in HelmDownloadClient

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/util/DigestUtils.kt

DigestUtils: avoid calling ByteBuffer.clear because of possible JDK incompatibility
fixes #34

Avoid possible JDK incompatibility about ByteBuffer.clear

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecWorkAction.kt

I've been making piecemeal fixes to missing env vars in the Gradle Worker API execution (based on the original pattern for the HOME env var from 1.2.0).  
This is a tedious process, and it is always possible, that a new required or important env var will need to be added.
Instead, I propose this change, which, according to my testing fixes the issue generally for all env vars.
The problem with the original code was that it was completely **overriding** the env vars **map** (i.e environment = parameters.environment) for the execution instead of simply adding or override the env vars provided by the HelmExecWorkParameters object.
Example execution after the fix (see how it now gets all my env vars)
```
Executing: [/tmp/junit6733491531394942849/build/helm/bin/helm, repo, add, --username, , …
```

General fix for missing Gradle Worker API environment vars

---

docs/managing-releases.adoc
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecProvider.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmCommandTask.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmStatus.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/HelmReleasesPlugin.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/rules/HelmStatusReleaseOnTargetTaskRule.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/rules/HelmStatusReleaseTaskRule.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmStatusTest.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/testutil/exec/StatefulVerification.kt

- added `HelmStatus` task type
- `helm-releases` plugin adds `helmStatus<Release>` and `helmStatus<Release>On<Target>` tasks

Release status checking

---

build.gradle.kts
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmReleaseTestOptions.kt

- Downgrade Dokka plugin back to 0.10.1 (incompatible with Kotlin 1.3)
- Upgrade Asciidoctor plugin to 3.2.0

Documentation upgrades/fixes

---

README.adoc
docs/prerequisites.adoc
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmRelease.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmReleaseTarget.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/rules/HelmInstallReleaseTaskRule.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/rules/HelmUninstallReleaseFromTargetTaskRule.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/rules/HelmUninstallReleaseTaskRule.kt

This will avoid the extra decorator object around `HelmRelease` and `HelmReleaseTarget` that was used to expose the `ExtensionAware`ness on those interfaces. Instead, these interfaces will extend `ExtensionAware` directly.
Unfortunately this means that we can no longer support Gradle 5.1, because it does not allow generated classes to implement `ExtensionAware` explicitly (unless they also implement `DynamicObjectAware`, which isn't really possible). Still, breaking support for Gradle 5.1 is probably less severe than breaking existing build scripts that rely on the `extra` properties being available.
fixes #85

Avoid decorator around HelmRelease and HelmReleaseTarget

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmValueOptions.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmInstallationCommandTask.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmLint.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/Linting.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmRelease.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmReleaseTarget.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/util/GradleVersions.kt

`ObjectFactory.fileCollection()` is only available since Gradle 5.3, for
Gradle 5.2 compatibility we have to use the now-deprecated `ProjectLayout.configurableFiles()`

Gradle compatibility: ConfigurableFileCollection factory method

---

build.gradle.kts

Upgrade AsciidoctorJ tabbed code extension to 0.3, old version does not work anymore with newer Asciidoctor plugin

Upgrade Asciidoctor tabbed code extension to 0.3

---

src/test/kotlin/org/unbrokendome/gradle/plugins/helm/testutil/exec/ExecMockServer.kt
src/test/kotlin/org/unbrokendome/gradle/plugins/helm/testutil/exec/ExecutableGradleExecMock.kt

Have a single lazy mock server that serves all exec mocks, distinguished by an invocation ID

Shared ExecMock in tests

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/dsl/HarborHelmPublishingRepository.kt
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/publishers/AbstractHttpHelmChartPublisher.kt

Hello!
Thanks a lot for the improvements you did with #101 to support Harbor. I hope it will be integrated in a new version soon!
I tested it with an instance of Harbor, but encountered `500` errors when the `POST` method is submitted to upload the chart. After digging a little, I realized that Harbor expects that the chart archive file is sent as `multipart/form-data`.
See API reference on that subject for Harbor 2.x (https://github.com/goharbor/harbor/blob/5f52168ee9e287beb6a6a48cdd1594153655b880/api/swagger.yaml#L92-L96) and Harbor 1.x (https://github.com/goharbor/harbor/blob/490042d8d9d29dd8095ac3396519ddcb9d2d39e1/api/harbor/swagger.yaml#L2999-L3003)
This PR fixes this requirement.

Fix Harbor chart POST requests

---

docs/configure-helm.adoc
src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/HelmDownloadClient.kt

Use latest Helm version (3.4.1) when downloading Helm client

Download client: Helm 3.4.1

---

build.gradle.kts
gradle.properties

Enable parallel (forked) tests to make testing faster
Use a Gradle project property so we run 4 tests in parallel by default, but can reset it to 1 for constrained environments

Enable parallel tests in build

---

build.gradle.kts

Use the new Dokka version (1.4.x) for generating documentation; requires Kotlin 1.4

Use the new Dokka version (1.4.x)

---

src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/dsl/HelmRelease.kt

Method getExtensions is not automatically implemented by Gradle class generator, so trying to access extensions will always throw an exception with the current implementation.

HelmRelease: do not implement ExtensionAware

---

helm-plugin/src/main/kotlin/org/gradle/kotlin/dsl/ExtensionAccessors.kt
helm-publish-plugin/src/main/kotlin/org/gradle/kotlin/dsl/ExtensionAccessors.kt

These files must be in the package org.gradle.kotlin.dsl so they do not have be imported in Gradle scripts. However, now that there are two plugin libraries defining that class, they have to use a unique class name to avoid collisions.
fixes #116

Fix: use unique class names for "ExtensionAccessors"

---

docs/defining-charts.adoc

The table of configuration options was missing column separators, so all the table content was lumped together into a single column.
Added column separators for better/cleaner layout.

fix(doc): table layout

---

docs/publishing-charts.adoc
helm-publish-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/dsl/GitlabHelmPublishingRepository.kt
helm-publish-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/dsl/HelmPublishingRepositoryContainer.kt

Add support for publishing [Helm charts in the Gitlab Package Registry](https://docs.gitlab.com/ee/user/packages/helm_repository/#helm-charts-in-the-package-registry).
Closes unbroken-dome/gradle-helm-plugin#132

Publishing: Gitlab support

---

docs/linting-charts.adoc
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmLint.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/Linting.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/rules/LintWithConfigurationTaskRule.kt
helm-plugin/src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmLintTest.kt

- Add `withSubcharts` property to `HelmLint` task (corresponding to `--with-subcharts` CLI flag)
- Add `withSubcharts` property to `Linting` DSL
- Pass the `withSubcharts` property to the task in `HelmLintTask` rule

Lint with subcharts

---

helm-plugin/build.gradle.kts
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/HelmChart.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/rules/FilterChartSourcesTaskRule.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/tasks/HelmFilterSources.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/util/YamlTransformingReader.kt
helm-publish-plugin/build.gradle.kts
helm-releases-plugin/build.gradle.kts

There is a bug in the DelegateReader (contributed by [gradle-plugin-utils](https://github.com/unbroken-dome/gradle-plugin-utils) library) which leads to reader exceptions being "swallowed" in some cases.
In the case of `SimpleTemplateEngineFilterReader` and `YamlTransformingFilterReader`, the whole input is read first before the delegate reader is created. If there is an error while reading the input, the outer `use` block tries to close the outer reader, which would then trigger the reading of the input again, leading to another "stream closed" IOException that would hide the original error. This is now fixed in gradle-plugin-utils 0.4.0.

Fix for DelegateReader swallowing exceptions

---

helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmDependenciesTask.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmBuildDependencies.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmUpdateDependencies.kt

Use overrides with different getter annotations instead of programmatically configuring task.inputs / task.outputs

Fix input properties of HelmBuildDependencies

---

helm-plugin/build.gradle.kts
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmUninstall.kt
helm-plugin/src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmBuildDependenciesTest.kt
helm-plugin/src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmUninstallTest.kt
helm-plugin/src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmUpdateDependenciesTest.kt
helm-publish-plugin/build.gradle.kts
helm-releases-plugin/build.gradle.kts
settings.gradle.kts

HelmUninstall now uses an `onlyIf` instead of `upToDateWhen` block to check whether the release exists.
This prevents the task from being executed anyway if any of the other inputs have changed, or if the task has never been executed.

skip uninstall if release does not exist

---

helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/HelmDownloadClientPackage.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/dsl/HelmDownloadClient.kt

End users are restricted to the project property to set a custom base URL. That's not an option if the Helm plugin is used as part of a convention plugin that preconfigures it.
This is the PR for https://github.com/unbroken-dome/gradle-helm-plugin/issues/137.

Expose Helm client download URL through DSL

---

docs/defining-charts.adoc

fix null tabs in documentation

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/internal/HelmValueOptions.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmInstallationCommandTask.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/rules/DefaultRenderingRule.kt
helm-publish-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/publishing/tasks/HelmPublishChart.kt

The goal is to get rid of API which isn't supported by the latest Gradle (as per as it was released recently). The easiest way to do this is to use the latest Gradle for compilation.

update gradle (and Kotlin), remove some deprecated API

---

docs/config-from-project-properties.adoc
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmCommandsPlugin.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmInstallationOptions.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/internal/HelmInstallationOptions.kt
helm-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/tasks/AbstractHelmInstallationCommandTask.kt
helm-plugin/src/test/kotlin/org/unbrokendome/gradle/plugins/helm/command/InstallationOptionsTests.kt
helm-releases-plugin/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/release/HelmReleasesPlugin.kt
helm-releases-plugin/src/test/kotlin/org/unbrokendome/gradle/plugins/helm/release/HelmReleasesPluginTest.kt

Support the `--skip-crds` flag that was added in Helm 3.1.2
* New property `skipCrds` on HelmInstall, HelmUpgrade and HelmTemplate tasks
* New property `skipCrds` on HelmRelease
* New Gradle project property `helm.skipCrds` for global default

Support `--skip-crds` flag
